---
title: Chat met vraag en antwoord
hero_image: images/banner.png
description: Maak een chatbot of een "niet-speler karakter (NPC)" met behulp van vraag- en antwoordblokken.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Chat met vraag en antwoord
