---
title: Chat using ask and answer
hero_image: images/banner.png
description: Create a chatbot or non-player character (NPC) using ask and answer blocks.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Chat using ask and answer
