---
title: Sgwrsio gan ddefnyddio gofyn ac ateb
hero_image: images/banner.png
description: Creu bot sgwrsio neu gymeriad nad yw'n chwaraewr (NPC) gan ddefnyddio blociau gofyn ac ateb.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Sgwrsio gan ddefnyddio gofyn ac ateb
