---
title: Conversa usando "pergunte" e "resposta"
hero_image: images/banner.png
description: Crie um chatbot ou um personagem não jogável (NPC) usando blocos de "pergunte" e "responda".
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Conversa usando "pergunte" e "resposta"
