---
title: Chat pomocí dotazů a odpovědí
hero_image: images/banner.png
description: Vytvořte si chatbota nebo nehrající postavu (NPC) pomocí bloků dotazů a odpovědí.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Chat pomocí dotazů a odpovědí
