---
title: Habla usando preguntas y respuestas
hero_image: images/banner.png
description: Crea un chatbot o un personaje no jugador (NPC por sus siglas en inglés) usando los bloques preguntar y respuesta.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Habla usando preguntas y respuestas
